# Generated by Django 2.1.7 on 2019-02-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190224_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='music.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music.Artist'),
        ),
    ]
