# Generated by Django 2.1.7 on 2019-02-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190224_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(help_text='.mp3', null=True, upload_to='songs'),
        ),
    ]
