# Generated by Django 2.1.7 on 2019-02-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music.Album'),
        ),
    ]
