# Generated by Django 2.1.7 on 2019-02-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190224_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='./static/media/albums'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(upload_to='./static/media/artists'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(upload_to='./static/media/playlists'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(help_text='.mp3', null=True, upload_to='./static/media/songs'),
        ),
    ]
