# Generated by Django 2.1.7 on 2019-03-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20190227_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(help_text='Allowed format - .mp3', null=True, upload_to='songs'),
        ),
    ]
