# Generated by Django 2.1.7 on 2019-07-19 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20190315_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='albums'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(upload_to='artists'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(upload_to='playlists'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(help_text='Allowed format - .mp3', null=True, upload_to='songs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
